### ISSUE TITLE
Add Send Coins Wallet Screen 

### ISSUE THREAD

**Issue by pivilartisant** [massalabs/thyra-plugin-wallet#229]
**Context**
In order to launch Massa Wallet, we must implement the send coins screens 

Attached [here](https://github.com/massalabs/ui-kit/issues/102) is the ui-kit meta issue that details the different components we need to implement

- [x] #312

![Screenshot from 2023-05-30 10-51-14](https://github.com/massalabs/thyra-plugin-wallet/assets/90157528/9b465051-ed87-44da-9173-79f560c4b351)

**Here are the steps to creation**

Url & routing : 
This page will be hosted here :  http://localhost:8080/web-app/homepage/{account-name}/send

Reminder : one page/url, one route. This route will render always the related name component. If we need to split in many, it will be inside of each related component.
-> this specific question will be dealt with in this [PR](https://github.com/massalabs/thyra-plugin-wallet/pull/259)

- [x] #262
- [x] #266
- [x] Refactor dashboard and implement it as a layout 
- [x] #272

Account Balance : 

![Screenshot from 2023-05-30 11-00-06](https://github.com/massalabs/thyra-plugin-wallet/assets/90157528/7a452c95-72d6-4b02-bf93-505379e1c92e)

- [x] #263
- [x] Implement backend account balance retrieval
- [x] Think about amount formating 

Amount Selection : 
![Screenshot from 2023-05-30 11-11-07](https://github.com/massalabs/thyra-plugin-wallet/assets/90157528/0301d16f-3ba2-4d39-aa60-bca1ab330085)

- [x] implement **frontend** components (percentages are a prio, token select is not)
- [x] implement **backend** amount validation (cf rules) & amount percentage selection

Recipient selection :

![Screenshot from 2023-05-30 10-57-47](https://github.com/massalabs/thyra-plugin-wallet/assets/90157528/1d80d9e1-99f7-44c3-82e0-2537f503ec2b)

- [x] implement frontend component  (transfer between accounts is a prio, contact list is not a prio)
- [x] Implement backend transfer between account list fetch
- [x] implement backend account format validation (see rules)

Advanced section :
![Screenshot from 2023-05-30 10-56-18](https://github.com/massalabs/thyra-plugin-wallet/assets/90157528/4f8aba9c-9410-4ab1-9566-f7e1d9630bc1)

- [x] Implement frontend components 
- [x] Implement backend gas fees fetch 

Transaction confirmation : 
![Screenshot from 2023-05-30 11-07-15](https://github.com/massalabs/thyra-plugin-wallet/assets/90157528/c36ff432-4e17-4e08-b50d-97e8e064e50c)

- [x] Implement frontend components 
- [x] Implement backend redirection to wails sign a transaction 

Sign a transaction :
![Screenshot from 2023-05-30 11-10-29](https://github.com/massalabs/thyra-plugin-wallet/assets/90157528/c76f595a-4f35-46a1-abb9-4f5c96150f1e)

- [x] Implement frontend wails sign a transaction
- [x] COnnect the web-frontend to the wails using the usePost method
- [x] Implement backend wails sign a transaction using the transfer protocol that is already implemented 

*** IMPLEMENTATION RULES ***  

Suggested URL: my.massa/massastation/wallet/XXX/send
Where XXX is the name of the account

Rules to implement:  * Send token field: amount format is: 
- XXX,XXX,XXX.XX (show the comma as a separator for thousands and the dot as a separator for number after the 0. User can add up to 9 numbers after the dot. 
Read: only 2 numbers after the dot
Write: up to 9 numbers after the dot (to match the blockchain rules)

25%; 50% etc... options: this is an easy-selection tool. 
When a user click on one of the number it automatically fulfil the amount field with the selected % of the total amount of the account.  Ex: As a user, when I click on 50% I want to see the amount field input completed with exactly 50% of my total account balance. 

Recipient field: 
- Step 1: Only Massa address format accepted.  --> on the click on “Send” do the format check that the address has a Massa format address or display error message: “This address doesn’t have the right format” 
- Step 2: Once contact page exists
Accept Massa address + existing contact name
--> on the click on “Send” do the checks.

Transfer between accounts: GET /rest/wallet/{nickname}

Display this text only if more than one account exist.  In the pop-up, display the list of existing accounts except the one user is currently using.
--> when user click on one account, the pop-up automatically close up and the account name appears on the “Recipient” field.

**Comment by SlnPons** [comment]
@pivilartisant Hey Paul, just saw this issue you created. It's great we have the list of tasks somewhere. But 2 comments:

The work described is not exactly correct. Simply because we'll break down the screen into different iterations to secure the basics first ;)
Check [this page](https://www.figma.com/file/LSaOibVDFb1reF6FePVn5l/Massastation?type=design&node-id=324-5834&t=ZtQNw8kA7DiXXTJ7-0) of the design, I added details and rules concerning this particular page.
Have a look and let's update this task together.

All the rules are defined on the design. Have a look and let me know if it's clear.
