### ISSUE TITLE
Make sure the wallet plugin is functional

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra-plugin-wallet#43]
**Context**
This issue is part of the 1st milestone to achieve for the Thyra squad working on the wallet plugin. See [here](https://www.notion.so/massa-innoteam/Wallet-85ec39b64f72481f98a0ff31c8a5608e?pvs=4#b67bc640e5414b328b64fe475658f428) for all details.

The objective of this issue is to make sure that all functionalities available in Thyra wallet are working well on this plugin.

**User flow**

1. User is able to create a wallet
1.1 By creating a new one (see image below with info asked) 
1.2 By importing an existing wallet (see image below with the info asked - NB: some info are asked by Thyra (private key & password) and others by the browser (nickname) to assure security.
2. Then user sees their wallet displayed w/ following info: nickname chosen, wallet address, balance
3. User is able to delete a wallet by clicking on the "X" 
4. User sees a message to confirm that he really wants to delete their wallet
5. User is able to receive coins and see the balance of its wallet updated

**How to**

- [ ] Once wallet plugin is connected to the new plugin manager, test - using both back-end and front-end - the functionalities listed above
- [ ] Validate the fact everything is working well and that we can safely remove Thyra wallet code 
Nice to have:

- [x] #59
- [x] https://github.com/massalabs/thyra-plugin-wallet/issues/31
- [x] https://github.com/massalabs/thyra-plugin-wallet/issues/16
- [ ] https://github.com/massalabs/thyra-plugin-wallet/issues/17
- [ ] https://github.com/massalabs/thyra-plugin-wallet/issues/19
- [ ] https://github.com/massalabs/thyra-plugin-wallet/issues/23

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Install the wallet plugin manually 
Use it using the front-end and manage to perform every possible action

**Comment by SlnPons** [comment]
@Thykof I can't install the wallet plugin properly so I'm struggling to help you on this.... :/ 

Let's correct the CI so that I can install and test the plugin functionally for you.

**Comment by SlnPons** [comment]
Will test this issue at the same time as the installation script + wallet. If everything is working well I'll put it in done today. Will keep you posted. But well done!!

**Comment by SlnPons** [comment]
yep, I put it in "done" but it doesn't close it ... my bad. Closing it now, thank you :) 
(btw, the 2 remaining points on this ticket are linked to what we discussed: rules that exist on the front-end but not on en back-end .... coincidence.... hmmm I don't think so 🤣)
