### ISSUE TITLE
Create export / back-up feature

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra-plugin-wallet#91]
**Context**
Part of mainnet plan - [Wallet product milestone 2](https://www.notion.so/massa-innoteam/Wallet-85ec39b64f72481f98a0ff31c8a5608e?pvs=4)

--> The objective of this issue is to create the possibility for users to back-up their wallet with different options

**User flow**
Follow the user flow described here: to be added

**How to**

API:
- [x] #101
- [x] #108
- [x] Create the endpoint to back-up a wallet by showing key pairs (? - nice-to-have)
- [x] #212

GUI (wails):
- [x] Create the ability to back-up a wallet by downloading the account file (yaml)
- [x] Create the ability to back-up a wallet by showing key pairs

**Technical details**
Wails implem:
the export of yml file is in => GET api/accounts{nickname}/exportFile
export of the wallet datas decrypted or not => GET api/accounts{nickname} with the parameter "ciphered" (bool)

As the choice of export method is done in wails, we must show the prompt first, then call the right endpoints according to the user choice.

we will create a new endpoint that will pop the wails prompter and create the wails userflow according the specification.

new endpoint:
GET api/accounts{nickname}/export
This endpoint will just wake up wails in "export" mode and return nothing.
The wails prompt should be executed asynchronously because we don't expect any return from this endpoint

**QA testing**
Follow the user flow
