### ISSUE TITLE
Transfer coins

### ISSUE THREAD

**Issue by SlnPons** [massalabs/thyra-plugin-wallet#92]
**Context**
Part of mainnet plan - [Wallet product milestone 2](https://www.notion.so/massa-innoteam/Wallet-85ec39b64f72481f98a0ff31c8a5608e?pvs=4)

--> the objective of this ticket is to add enable the transfer of coins between 2 wallets.

**User flow**

Follow the designs here: TO BE ADDED

User must see the total amount of the tx clearly

**How to**

- [x] #130
- [x] #163 
- [x] Update the wallet GUI to surface the description / info about the tx that needs to be signed (ie: the coins transfers between address X to address Y)
- [x] Introduce the gas fees (see comment bellow)
- [x] Create front-end as design

Transaction fee: 
- low: 1 NanoMas
- medium: 1000 NanoMas
- High: 5000 NanoMas

**Technical details**
*Give the technical insights so anyone in the team can tackle the tasks - Dev*

**QA testing**
Follow user flow designed

**Comment by gregLibert** [comment]
@SlnPons the MAS will never be indexed to USD or EUR. This being said, multiple exchange plateforms will propose different exchange rates.

**Comment by Thykof** [comment]
> @SlnPons the MAS will never be indexed to USD or EUR. This being said, multiple exchange plateforms will propose different exchange rates.

I propose to create a package that returns a USD price given a MAS amount, and implement for now 1:1 exchange rate. So that later we could link to real exchange rate.
By package I mean a folder in /pkg golang source code of the wallet plugin

**Comment by Thykof** [comment]
no, I wan to create a function in golang that convert MAS to USD, and implement a dummy exchange rate of 1:1. So that the floor is ready when we will have exchange plateforms.

**Comment by SlnPons** [comment]
@Thykof , @gregLibert fyi - my question was to understand what was plan for the mainnet as, let's be honest, we have very few details on that part so building a wallet with appropriate level of details is complicated. 
That is said, if we won't have this it's not a problem at all we won't add this feature in our wallet v1 :) 

@Thykof please keep in mind that designs are here to represent the big picture of a product (the end vision of it) and not the iterative way we'll build the product versions ;)

**Comment by SlnPons** [comment]
If this still block to be started? 
To date, we're late compare to the plan to we need to be very specific about what needs to be clarified so we can move on quickly :) Cheers

**Comment by Thykof** [comment]
as agreed together, we will not show to the user the USD amount.

**Comment by SlnPons** [comment]
Use case to cover: 
As a user, I want to transfer coins from wallet A to wallet B. To perform this action I have to pay a certain amont of gas fees that I want to be able to define prior to validate the tx and with the help of Massa to understand what I should put.

Market standard: most of the time users have 3 options a default one, time-based one or an advance one. 
* default one: gas fees are defined by default by the app. The info is shared with users but they can't change the default value.
* time-based one: users are given the option to choose between 3 options: fast / medium / slow which is the speed in which the tx will be validated (on Ethereum). The faster the more you pay. 
* an advance one: users can define themselves the amont of gas fees they want to pay. 

On Massa blockchain, and based on my understanding, the tx has a limited period of time to be accepted (= 1 cycle = 34 min) or it won't be accepted at all.
--> A time-based option is not that relevant. Compare to other blockchain, the time you have to wait is very small (even compare to current banking system). 
A default and advance options still make sense. Advance, only a few people will be able to define this but ... they can if they want. Default, we'll define this number based on... tbd (past tx as some suggested). 
@qdrn @AurelienFT can you confirm me that `On Massa blockchain, and based on my understanding, the tx has a limited period of time to be accepted (= 1 cycle = 34 min) or it won't be accepted at all.` is true?
And could you tell me for how many periods in the futur a transaction can live? (en français pour etre plus claire: est-ce qu'une tx peut vivre sur plusieurs period? Et si oui, sur combien?) 

Thanks

Happy to jump on a call if it's not clear!

**Comment by qdrn** [comment]
> @qdrn @AurelienFT can you confirm me that `On Massa blockchain, and based on my understanding, the tx has a limited period of time to be accepted (= 1 cycle = 34 min) or it won't be accepted at all.` is true? And could you tell me for how many periods in the futur a transaction can live? (en français pour etre plus claire: est-ce qu'une tx peut vivre sur plusieurs period? Et si oui, sur combien?)
I believe it can live over multiple periods. It can live for a maximum number of periods (don't have the specific number in mind).

**Comment by SlnPons** [comment]
Thanks @qdrn. It's indeed what I'm trying to understand a bit better to define appropriate vocabulary. In Massa, I don't think the time makes sense, I would like to introduce the idea of tips (for the validator) which makes more sense as even when the network will be overloaded the time will remain quite acceptable compare to others. 

Would you agree with this statement?

**Comment by AurelienFT** [comment]
To bring a bit of clarity on the inclusion of operations in the blocks.

When you send an operation to be included you specify a fee and an expire_period. Let's start with the fee : 

When a block producer wants to create a new block he wants to maximize his benefit and he has two constraints: the space in a block (1 MB) and the maximum of gas allow in a block execution (3 billion). He need to choose which operation he will include to gain the maximum number of fee. So there is some kind of ratio between the fee passed / space the op take and gas it cost.

About : 

> A time-based option is not that relevant

Yes when the blockchain isn't fully loaded (and that's will be complicated for Massa) but once it's the case, by looking at the previous blocks etc you can try to estimate when the gas market will go up and down and so give some indications like `fast` `slow` etc

Let's continue with expire_period :

The expire_period give a maximum amount of period for the operation to be included in a block. After this amount of period the operation will be deleted from the pool and can't be included in a block anymore. This value isn't 1 cycle but it's the user that choose when he sends the operation.

We also use the `expire_period` to ensure that this operation can't be included twice. You can't include once again the same operation before the end of the `expire_period`.

To avoid people placing `u64::MAX` as expire period and force us to keep the op in our executed cache forever, we allow an operation to be included in a block only 10 periods before the `expire_period`.

Example : We are at period 1. You send an operation with `expire_period` 20. Then your operation can be included in block of period 10 at the best.

**Comment by SlnPons** [comment]
@Thykof could you break this ticket down a little bit to show what you're doing exactly. I'm a bit lost 😅

**Comment by Thykof** [comment]
I have create this new ticket https://github.com/massalabs/thyra-plugin-wallet/issues/130

**Comment by qdrn** [comment]
I would put 1 nano Massa for low. Chances are some nodes will reject 0 fees transactions and 1 nano Massa is basically nothing already.
